apiVersion: v1
kind: Service
metadata:
  name: recipe-cookbook-api-service
spec:
  type: LoadBalancer
  selector:
    app: recipe-cookbook-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3080
