apiVersion: v1
kind: Service
metadata:
  name: recipe-cookbook-api-service
spec:
  selector:
    app: RecipeCookbookApi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3080
  type: LoadBalancer
